AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 13

