AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 45

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 260

Metrics/CyclomaticComplexity: 
  Max: 12